# Generated by Django 4.0.1 on 2022-01-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko', models.CharField(max_length=45)),
                ('imie', models.CharField(max_length=45)),
                ('id_pracownika', models.CharField(max_length=12)),
            ],
        ),
    ]
