# Generated by Django 4.0.1 on 2022-01-10 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jednostka_organizacyjna', '0001_initial'),
        ('uzytkownik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='jednostka_organizacyjna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jednostka_organizacyjna.jednostka_organizacyjna'),
        ),
    ]
