# Generated by Django 3.2.8 on 2022-01-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pojazd', '0003_auto_20220111_2130'),
        ('uzytkownik', '0002_uzytkownik_jednostka_organizacyjna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspekcji', models.DateField()),
                ('stan_licznika', models.IntegerField()),
                ('ogumienie_rodzaj', models.CharField(choices=[('L', 'letnie'), ('Z', 'zimowe'), ('W', 'wielosezonowe')], max_length=24)),
                ('ogumienie_stan', models.CharField(choices=[('dobry', 'dobry'), ('dopuszczalny', 'dopuszczalny'), ('zly', 'zly')], max_length=24)),
                ('oswietlenie', models.CharField(choices=[('sprawne', 'sprawne'), ('niesprawne', 'niesprawne')], max_length=24)),
                ('szyby_lusterka', models.CharField(choices=[('uszkodzone', 'uszkodzone'), ('nieuszkodzone', 'nieuszkodzone')], max_length=24)),
                ('nadwozie', models.CharField(choices=[('uszkodzone', 'uszkodzone'), ('nieuszkodzone', 'nieuszkodzone')], max_length=24)),
                ('silnik', models.CharField(choices=[('sprawny', 'sprawny'), ('niesprawny', 'niesprawny')], max_length=24)),
                ('wnetrze', models.CharField(choices=[('uszkodzone', 'uszkodzone'), ('nieuszkodzone', 'nieuszkodzone')], max_length=24)),
                ('wyposazenie', models.CharField(choices=[('kompletne', 'kompletne'), ('niekompletne', 'niekompletne')], max_length=24)),
                ('pojazd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pojazd.pojazd')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uzytkownik.uzytkownik')),
            ],
        ),
    ]
