# Generated by Django 4.0.1 on 2022-01-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jednostka_Organizacyjna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('miejscowosc', models.CharField(max_length=45)),
                ('ulica', models.CharField(max_length=45)),
                ('numer_domu', models.CharField(max_length=12)),
            ],
        ),
    ]
