# Generated by Django 3.2.8 on 2022-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty_paliwowe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karty_paliwowe',
            name='data_waznosci_karty',
            field=models.DateField(blank=True),
        ),
    ]
