# Generated by Django 3.2.8 on 2022-01-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pojazd', '0002_pojazd_masa_wlasna_alter_pojazd_numer_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badanie_Techniczne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_badania', models.DateField()),
                ('stan_licznika', models.IntegerField()),
                ('data_nastepnego_badania', models.DateField()),
                ('pojazd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pojazd.pojazd')),
            ],
        ),
    ]
