# Generated by Django 4.0.1 on 2022-01-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uzytkownik', '0002_uzytkownik_jednostka_organizacyjna'),
        ('jednostka_organizacyjna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_rejestracyjny', models.CharField(max_length=10)),
                ('marka', models.CharField(max_length=45)),
                ('typ', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('rodzaj', models.CharField(max_length=45)),
                ('podrodzaj', models.CharField(max_length=45)),
                ('kategoria', models.CharField(max_length=45)),
                ('rok_produkcji', models.IntegerField()),
                ('data_pierwszej_rejestracji', models.DateField()),
                ('numer_vin', models.CharField(max_length=12)),
                ('przeznaczenia', models.CharField(max_length=45)),
                ('numer_dowodu_rejestracyjnego', models.CharField(max_length=12)),
                ('numer_karty_pojazdu', models.CharField(max_length=12)),
                ('organ_wydajacy', models.CharField(max_length=45)),
                ('numer_swiadectwa_homologacji', models.CharField(max_length=45)),
                ('rodzaj_paliwa', models.CharField(choices=[('Pb', 'Pb'), ('ON', 'ON'), ('Pb + LPG', 'Pb + LPG')], max_length=12)),
                ('liczba_miejsc', models.IntegerField()),
                ('hak', models.CharField(choices=[('T', 'TAK'), ('N', 'NIE')], default='N', max_length=3)),
                ('pojemnosc_silnika', models.IntegerField()),
                ('moc_silnika', models.IntegerField()),
                ('masa_calkowita', models.IntegerField()),
                ('ladownosc', models.IntegerField()),
                ('jednostka_organizacyjna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jednostka_organizacyjna.jednostka_organizacyjna')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uzytkownik.uzytkownik')),
            ],
        ),
    ]
