# Generated by Django 4.0.1 on 2022-01-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='masa_wlasna',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='numer_vin',
            field=models.CharField(max_length=24),
        ),
    ]
