# Generated by Django 3.2.8 on 2022-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazd', '0002_pojazd_masa_wlasna_alter_pojazd_numer_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='kategoria',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='ladownosc',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='liczba_miejsc',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='masa_calkowita',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='moc_silnika',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='numer_swiadectwa_homologacji',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='podrodzaj',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='pojemnosc_silnika',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='przeznaczenia',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='rodzaj_paliwa',
            field=models.CharField(choices=[('Pb', 'Pb'), ('ON', 'ON'), ('Pb + LPG', 'Pb + LPG'), ('PRZYCZEPA', 'PRZYCZEPA')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='typ',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
