# Generated by Django 4.0.1 on 2022-01-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazd', '0003_auto_20220111_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia'),
        ),
    ]
