# Generated by Django 4.0.1 on 2022-01-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazd', '0004_pojazd_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='rok_produkcji',
            field=models.IntegerField(null=True),
        ),
    ]
