# Generated by Django 4.0.1 on 2022-01-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazd', '0005_alter_pojazd_rok_produkcji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='data_pierwszej_rejestracji',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='numer_dowodu_rejestracyjnego',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='numer_karty_pojazdu',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='numer_vin',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='organ_wydajacy',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='rodzaj_paliwa',
            field=models.CharField(choices=[('Pb', 'Pb'), ('ON', 'ON'), ('Pb + LPG', 'Pb + LPG'), ('PRZYCZEPA', 'PRZYCZEPA')], max_length=12, null=True),
        ),
    ]
