# Generated by Django 4.0.1 on 2022-01-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojazd', '0008_alter_pojazd_pojemnosc_silnika'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojazd',
            old_name='przeznaczenia',
            new_name='przeznaczenie',
        ),
    ]
