# Generated by Django 4.0.1 on 2022-01-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownik', '0002_uzytkownik_jednostka_organizacyjna'),
        ('jednostka_organizacyjna', '0001_initial'),
        ('pojazd', '0009_rename_przeznaczenia_pojazd_przeznaczenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='data_pierwszej_rejestracji',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='jednostka_organizacyjna',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jednostka_organizacyjna.jednostka_organizacyjna'),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='ladownosc',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='liczba_miejsc',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='marka',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='masa_calkowita',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='masa_wlasna',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='moc_silnika',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='model',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='numer_dowodu_rejestracyjnego',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='numer_karty_pojazdu',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='numer_vin',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='organ_wydajacy',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='pojemnosc_silnika',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='rodzaj',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='rodzaj_paliwa',
            field=models.CharField(choices=[('Pb', 'Pb'), ('ON', 'ON'), ('Pb + LPG', 'Pb + LPG'), ('PRZYCZEPA', 'PRZYCZEPA')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='rok_produkcji',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='uzytkownik',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='uzytkownik.uzytkownik'),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='zdjecia'),
        ),
    ]
