# Generated by Django 3.2.8 on 2022-01-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pojazd', '0002_pojazd_masa_wlasna_alter_pojazd_numer_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubezpieczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubezpieczyciel', models.CharField(max_length=45)),
                ('rodzaj_polisy', models.CharField(max_length=45)),
                ('numer_polisy', models.CharField(max_length=45)),
                ('data_poczatku_ubezpiezenie', models.DateField()),
                ('data_konca_ubezpieczenia', models.DateField()),
                ('pojazd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pojazd.pojazd')),
            ],
        ),
    ]
