# Generated by Django 3.2.8 on 2022-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='rodzaj_polisy',
            field=models.CharField(choices=[('OC', 'OC'), ('AC', 'AC'), ('ZIELONA_KARTA', 'ZIELONA_KARTA')], max_length=45),
        ),
    ]
