# Generated by Django 3.2.8 on 2022-01-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pojazd', '0002_pojazd_masa_wlasna_alter_pojazd_numer_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koszty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_powstania_kosztu', models.DateField()),
                ('kwota_netto', models.IntegerField()),
                ('stan_licznika', models.IntegerField()),
                ('numer_dokumentu', models.CharField(max_length=45)),
                ('rodzaj_kosztow', models.CharField(choices=[('koszty_paliwa', 'koszty_paliwa'), ('koszty_ubezpieczenia', 'koszty_ubezpieczenia'), ('koszty_przegladu', 'koszty_przegladu'), ('koszty_naprawy', 'koszty_naprawy'), ('koszty_wyposazenia', 'koszty_wyposazenia'), ('inne_koszty', 'inne_koszty')], max_length=45)),
                ('pojazd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pojazd.pojazd')),
            ],
        ),
    ]
